In [1]:
import numpy as np

In [19]:
with open("./mobydick.txt", 'rb') as fp:
    bytes = np.fromfile(fp, dtype = np.uint8)

In [20]:
bytes.min(), bytes.max()

(10, 226)

In [21]:
bytes.size

1256739

In [22]:
np.unique(bytes, return_counts = True)

(array([ 10,  13,  32,  33,  36,  38,  40,  41,  42,  44,  45,  46,  48,
         49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  63,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         93,  95,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
        108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 128, 130, 132, 146, 147, 148, 149, 151, 152, 153, 156,
        157, 162, 163, 166, 168, 169, 176, 183, 185, 191, 194, 195, 197,
        206, 207, 215, 226], dtype=uint8),
 array([ 22242,  22242, 194354,   1755,      2,      6,    215,    215,
            49,  19262,   2587,   7681,    109,     93,     37,     23,
            19,     34,     18,     34,     39,     16,    198,   4177,
          1003,   2473,   1375,   1259,    656,    971,    727,    543,
          1416,   3629,    250,    140,    797,    642,    888,    637,
          113

In [34]:
np.array(np.unique(bytes, return_counts = True))[:,0]

array([   10, 22242], dtype=int64)