In [11]:
import numpy as np
np.random.seed(2024 - 3 - 21)

In [12]:
# x is an identity matrix

x = np.matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
x

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [13]:
# 4 x 4 identity matrix

np.eye(N = 4, M = 4, dtype = np.int64)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [17]:
# a 4 x 3 matrix

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# in matrix multiplication, the number of columns of the first matrix and the number of rows of the second matrix must be the same
# the resulting matrix will have number of rows of the first matrix
# and the number of columns of the second matrix

In [23]:
np.matmul(a, b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [22]:
np.matmul(b, a)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])