In [15]:
import numpy as np
import torch
from PIL import Image
import matplotlib.pyplot as plt

In [4]:
x = np.random.randint(low = 0, high = 10_000, size = (1000, 1000))

In [7]:
torch.cuda.is_available()

True

In [6]:
torch.tensor(x, dtype = torch.int64)

tensor([[1232, 1760, 8934,  ..., 9463, 7398, 8399],
        [8798, 8473,  262,  ...,  394, 2295, 6018],
        [8497, 5185, 6297,  ..., 6622, 3612, 7022],
        ...,
        [8084, 6055, 7156,  ...,  975, 3881,  449],
        [ 854, 8900, 5579,  ..., 7298, 8918, 7517],
        [8596, 4798, 7250,  ..., 3537, 3218, 8941]])

In [10]:
y = torch.tensor(x, dtype = torch.float64, device = torch.device("cuda:0"))
y

tensor([[1232., 1760., 8934.,  ..., 9463., 7398., 8399.],
        [8798., 8473.,  262.,  ...,  394., 2295., 6018.],
        [8497., 5185., 6297.,  ..., 6622., 3612., 7022.],
        ...,
        [8084., 6055., 7156.,  ...,  975., 3881.,  449.],
        [ 854., 8900., 5579.,  ..., 7298., 8918., 7517.],
        [8596., 4798., 7250.,  ..., 3537., 3218., 8941.]], device='cuda:0',
       dtype=torch.float64)

In [11]:
y.sum()

tensor(5.0006e+09, device='cuda:0', dtype=torch.float64)

In [13]:
y.shape

torch.Size([1000, 1000])

In [14]:
y.flatten().shape

torch.Size([1000000])

In [35]:
with open(r"./girl.jpg", mode = "rb") as fp:
    girl = np.fromfile(fp, dtype = np.uint8)

In [37]:
girl.size

687321

In [38]:
girl.shape

(687321,)

In [39]:
torch.tensor(girl, device = torch.device("cuda:0"), dtype = torch.uint8)

tensor([255, 216, 255,  ...,  67, 255, 217], device='cuda:0',
       dtype=torch.uint8)