In [32]:
import numpy as np
import PIL

## ___Prototyping a JPEG decoder___
-----------------------

![](./jpegrgb_dissected.png)

In [49]:
with open("./alesia_riabenkova_black_and_white-wallpaper-5120x3200.jpg",mode = "rb") as fp:
    alesia = np.fromfile(fp, dtype = np.uint8)

with open("./alesia_riabenkova_black_and_white-wallpaper-5120x3200.jpg",mode = "rb") as fp:
    alesia_16 = np.fromfile(fp, dtype = np.uint16)

In [50]:
# we have the byte stream of the .jpeg file :)

alesia.size

4888175

In [51]:
print(0xFF, 0xD8)

255 216


In [52]:
# start of image (2 bytes)

alesia[:2]

array([255, 216], dtype=uint8)

In [60]:
# application default header (2 bytes) marker

alesia[2:4]

array([255, 224], dtype=uint8)

In [62]:
# default header contents (16 bytes)

alesia[4:20]

array([ 0, 16, 74, 70, 73, 70,  0,  1,  1,  0,  0,  1,  0,  1,  0,  0],
      dtype=uint8)

In [74]:
# 74, 70, 73, 70, 0 is JFIF\0 (C's null terminator)

alesia[6:11].tobytes().decode()

'JFIF\x00'

In [92]:
0x48

72

In [68]:
# quantization table marker 

alesia[20:22]

array([255, 254], dtype=uint8)

In [69]:
# quantization table contents (67 bytes)

alesia[22:89]

array([  0,  59,  67,  82,  69,  65,  84,  79,  82,  58,  32, 103, 100,
        45, 106, 112, 101, 103,  32, 118,  49,  46,  48,  32,  40, 117,
       115, 105, 110, 103,  32,  73,  74,  71,  32,  74,  80,  69,  71,
        32, 118,  54,  50,  41,  44,  32, 113, 117,  97, 108, 105, 116,
       121,  32,  61,  32,  57,  53,  10, 255, 219,   0,  67,   0,   2,
         1,   1], dtype=uint8)

In [82]:
alesia[89:200]

array([  1,   1,   1,   2,   1,   1,   1,   2,   2,   2,   2,   2,   4,
         3,   2,   2,   2,   2,   5,   4,   4,   3,   4,   6,   5,   6,
         6,   6,   5,   6,   6,   6,   7,   9,   8,   6,   7,   9,   7,
         6,   6,   8,  11,   8,   9,  10,  10,  10,  10,  10,   6,   8,
        11,  12,  11,  10,  12,   9,  10,  10,  10, 255, 219,   0,  67,
         1,   2,   2,   2,   2,   2,   2,   5,   3,   3,   5,  10,   7,
         6,   7,  10,  10,  10,  10,  10,  10,  10,  10,  10,  10,  10,
        10,  10,  10,  10,  10,  10,  10,  10,  10,  10,  10,  10,  10,
        10,  10,  10,  10,  10,  10,  10], dtype=uint8)

In [79]:
0xFF, 0xDB, 0xE0

(255, 219, 224)

In [78]:
np.where(0xFFDB == alesia_16)

(array([ 176797,  214058,  571537,  582714,  588693,  589361,  658245,
         663563,  688351,  786157, 1030076, 1031089, 1039593, 1199007,
        1247195, 1437831, 1449990, 1506074, 1629912, 1685748, 1689630,
        1721805, 1772748, 1780407, 1808164, 1883984, 1964643, 2020754,
        2034650, 2263110, 2396393, 2429660], dtype=int64),)

In [83]:
alesia_cpy = alesia.copy()

In [84]:
rands = np.random.randint(low = 0, high = 255, size = alesia.size)

for i in range(200, alesia.size, 20):
    alesia_cpy[i] = rands[i]

In [87]:
with open("./demi_lovato_sorry_not_sorry-wallpaper-5120x3200.jpg", "rb") as fp:
    demi = np.fromfile(fp, dtype = np.uint8)

In [88]:
demi.size

4774391

In [89]:
demi[:2]

array([255, 216], dtype=uint8)

In [90]:
demi[2:4]

array([255, 224], dtype=uint8)

In [91]:
demi[4:20]

array([ 0, 16, 74, 70, 73, 70,  0,  1,  1,  0,  0,  1,  0,  1,  0,  0],
      dtype=uint8)

In [93]:
demi[20:22]

array([255, 254], dtype=uint8)

In [39]:
# end of image

alesia[-2:]

array([255, 217], dtype=uint8)