In [1]:
from sklearnex import patch_sklearn
patch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [102]:
from sklearnex.neighbors import KNeighborsClassifier
from sklearnex.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder, LabelBinarizer
from sklearnex.model_selection import train_test_split
from sklearn.metrics import accuracy_score   # vanila sklearn, sklearnex doesn't have accuracy_score
import numpy as np
import pandas as pd
from scipy.io import arff

In [9]:
df = pd.DataFrame(arff.loadarff("./phpCsX3fx.arff")[0])

In [12]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'Class'],
      dtype='object')

In [21]:
df.Class = df.Class.apply(lambda x: np.int64(x))

In [26]:
df

V1        V2        V3        V4        V5        V6        V7  ...       V59       V60       V61       V62       V63       V64  Class
0     0.003906  0.003906  0.027344  0.033203  0.007812  0.017578  0.023438  ...  0.027344  0.033203  0.001953  0.000000  0.017578  0.000000      1
1     0.005859  0.013672  0.027344  0.025391  0.013672  0.029297  0.019531  ...  0.046875  0.005859  0.003906  0.003906  0.046875  0.000000      1
2     0.011719  0.001953  0.027344  0.044922  0.017578  0.042969  0.023438  ...  0.056641  0.009766  0.003906  0.000000  0.015625  0.000000      1
3     0.013672  0.011719  0.037109  0.017578  0.011719  0.087891  0.023438  ...  0.033203  0.003906  0.000000  0.001953  0.027344  0.000000      1
4     0.007812  0.009766  0.027344  0.025391  0.001953  0.005859  0.015625  ...  0.056641  0.019531  0.000000  0.000000  0.013672  0.000000      1
...        ...       ...       ...       ...       ...       ...       ...  ...       ...       ...       ...       ...       ...       ...    ...
1595  0.035156  0.027344  0.005859  0.005859  0.007812  0.027344  0.035156  ...  0.003906  0.011719  0.000000  0.015625  0.003906  0.000000      3
1596  0.015625  0.009766  0.000000  0.001953  0.015625  0.033203  0.080078  ...  0.007812  0.009766  0.000000  0.035156  0.003906  0.015625      3
1597  0.013672  0.005859  0.007812  0.003906  0.015625  0.013672  0.078125  ...  0.003906  0.013672  0.000000  0.037109  0.009766  0.009766      3
1598  0.015625  0.015625  0.011719  0.000000  0.007812  0.015625  0.060547  ...  0.000000  0.017578  0.000000  0.011719  0.003906  0.009766      3
1599  0.019531  0.013672  0.007812  0.001953  0.007812  0.025391  0.046875  ...  0.003906  0.007812  0.003906  0.029297  0.005859  0.031250      3

[1600 rows x 65 columns]

In [36]:
df.shape

(1600, 65)

In [38]:
x = df.iloc[:, : df.shape[1] - 1]
y = df.iloc[:, df.shape[1] - 1]

In [57]:
sscaler = StandardScaler()
x = sscaler.fit_transform(x)

In [58]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.3)

In [63]:
knn = KNeighborsClassifier(n_neighbors = 10, n_jobs = 8, leaf_size = 10, p = 10)

In [65]:
knn.fit(train_x, train_y)

KNeighborsClassifier(leaf_size=10, n_jobs=8, n_neighbors=10, p=10)

In [66]:
knn.predict(test_x)

array([ 44,   1,  18,  63,  28,  45,  62,  77,  93,  39,  99,  64,  47,
        23,  42,  59,  98,  77,  61,  69,  82,  37,  80,  36,  68,   5,
        16,  46,   7,  38,  13,  72,  85,  73,  85,  12,  64,  79,  23,
        92,  33,  75,  10,  96,  48,  76,  29,  70,  98,  75,   1,   1,
        19,  56,  20,  22,  56,  50,  15,  65,   2,  68,  42,   4,  66,
        85,   7,  79,  29,   2,   4,  71,  76,  25,  13,  12,   9,  14,
        71,  50,  15,  13,  19,  55,  13,  56,  13,  51,  40,  22,  31,
        44,  29,  63,  85,  53,  44,  30,   5,  14,  75,  12,  24,  29,
        85,  83,  73,   6,  52,  22,  51,  21,  46,   3,  55,  25,  84,
        82,   1,  77,  43,  81,  10,  42,  67,  49,  27,  56,  95,  93,
        76,  74,  92,  71,  77,  99,  13,  13,  69,  63,  92,  87,  23,
        11,  20,  51,  70,  40,  92,  96,  51,  51,  56,  45,  52,  93,
        56,  56,  40,  74,  78,   9,  68,  10,  67,  46,   6,  20,  70,
        85,  40,  24,  64,  31,  12,  58,  55,  13,  72,   8,  1

In [68]:
lreg = LinearRegression(n_jobs = 8)

In [69]:
lreg.fit(train_x, train_y)

LinearRegression(n_jobs=8)

In [71]:
lreg.coef_

array([ -8634.47047506, -16977.9346628 , -11323.82808742, -12532.53076658,
        -8011.70430891, -22739.55568597,  -7618.07771812,  -1199.24810008,
        -4021.44153888,  -7084.05612011, -11432.60703349,  -5226.62172302,
       -20428.27622097,  -5615.1234629 ,  -6303.42379121,   -661.62404135,
        -4801.77591604,  -9988.5263502 ,  -6248.95643144,  -4374.58120802,
        -8416.84094282,  -4516.07385125,  -1954.3931008 ,  -5486.77775967,
        -5575.16695645,  -5344.19364229,  -4814.50368962,  -6159.1073724 ,
       -10095.68514088,  -7196.09791135,  -7300.28417656,  -8458.31704598,
        -7023.48128207,  -1006.37024124,  -5984.89479443,  -7126.69986495,
        -4974.41001353, -10167.94302508,  -5871.74987315,  -4673.85280235,
       -10081.12682884,  -6534.29146166,  -9238.23110991,  -5100.29359729,
       -10785.84081221,  -5726.39036887,  -9432.12075052, -13258.98923983,
        -7038.50685084,  -7609.39533615, -10824.69590409,  -3239.76715905,
        -7990.70899092,  

In [73]:
lreg.predict(test_x)

array([ 52.10985959,  46.11050223,  27.69317875,  74.46527262,
        55.32394957,  33.36172868,  43.30889494,  72.83151881,
        46.81011727,  26.81687404,  48.41315627,  70.83286145,
        22.7222634 ,  63.214894  ,  67.84957299,  75.14522342,
        68.1175557 ,  78.44992953,  56.91603304,  69.55539733,
        84.52777751,  35.92227143,  72.44062564,  40.21464479,
        70.05404698,  62.08799903,  60.21295028,  41.43413015,
        43.71627337,  40.9301197 ,  58.94512174,  66.62753401,
        74.97845661,  62.44911142,  56.44409975,  47.93641724,
        58.24859766,  74.82689149,  57.23230458,  81.12500761,
        43.01870198,  57.12155327,   8.56399529,  61.51094859,
        56.66153257,  74.61209286,  65.11553974,  64.82044993,
        39.48354246,  66.63080634,  66.34818572,  62.56450038,
        55.90755524,  41.81221533,  35.00963176,  55.49244261,
        30.00269732,  57.38852648,  46.78130855,  40.81893037,
        44.66367958,  60.48741071,  43.31052984, -24.56

In [74]:
# that dataset sucked big time!

In [78]:
rice = pd.DataFrame(arff.loadarff("./Rice_Cammeo_Osmancik.arff")[0])

In [81]:
rice.columns

Index(['Area', 'Perimeter', 'Major_Axis_Length', 'Minor_Axis_Length',
       'Eccentricity', 'Convex_Area', 'Extent', 'Class'],
      dtype='object')

In [83]:
rice_x = sscaler.fit_transform(rice.iloc[:, : rice.shape[1] - 1])

In [87]:
rice.Class.unique()

array([b'Cammeo', b'Osmancik'], dtype=object)

In [91]:
rice_y = LabelEncoder().fit_transform(rice.Class)

In [95]:
rice_train_x, rice_test_x, rice_train_y, rice_test_y = train_test_split(rice_x, rice_y, test_size = 0.3)

In [98]:
preds = KNeighborsClassifier(n_jobs = 16).fit(rice_train_x, rice_train_y).predict(rice_test_x)

In [100]:
# wow!

accuracy_score(preds, rice_test_y)

0.9203849518810149

In [103]:
preds = LinearRegression(n_jobs = 16).fit(rice_train_x, rice_train_y).predict(rice_test_x)

In [104]:
accuracy_score(preds, rice_test_y)

ValueError: Classification metrics can't handle a mix of continuous and binary targets

In [107]:
preds = LogisticRegression(max_iter = 1000, n_jobs = 16).fit(rice_train_x, rice_train_y).predict(rice_test_x)

In [109]:
# that's a little better

accuracy_score(preds, rice_test_y)

0.9326334208223972

In [111]:
bean = pd.read_csv("./Dry_Bean_Dataset.csv")

In [113]:
bean.shape

(13611, 17)

In [115]:
bean_x = StandardScaler().fit_transform(bean.iloc[:, : bean.shape[1] - 1])

In [116]:
bean_y = LabelEncoder().fit_transform(bean.iloc[:, 16])

In [118]:
np.unique(bean_y)

array([0, 1, 2, 3, 4, 5, 6])

In [119]:
train_x, test_x, train_y, test_y = train_test_split(bean_x, bean_y)

In [123]:
preds = LogisticRegression(n_jobs = 16, max_iter = 1000).fit(train_x, train_y).predict(test_x)

In [125]:
# that truly is impressive.

accuracy_score(preds, test_y)

0.9188950925653835

In [ ]:
# I haven't forgotten this ML stuff after all.